#!/bin/bash
# Compile and set up the code ready to run in a separate directory
# usage:  ./make3dgp 

#Take care of any params.in changes
if [ -a params.in ]; then
	cp params.in $GP3DSOURCELOC
else
	cp $GP3DSOURCELOC/params.in.dist $GP3DSOURCELOC/params.in
fi
#Change to code dir
origdir=${PWD}
pushd $GP3DSOURCELOC
#Compile.
make
#Setup dir
#if [ $? == 0 ]; then
mv gp $origdir
cp params.in run.sh $origdir
rm *.mod params.in
#fi
make clean
#go back
popd
chmod +x gp
chmod +x run.sh
