#!/bin/bash
# Compile and set up the code ready to run in a separate directory
# usage:  ./make3dgp TYPE

if [ -z $1 ]; then
	TYPE="sh"
elif [ $1 = "qsub" -o $1 = "slurm" ]; then
	TYPE="$1"
else
	echo "Usage:  ./make3dgp TYPE";
	echo 'TYPE can be "sh", "qsub" or "slurm"';
	exit 1
fi

#Take care of any params.in changes
if [ -a params.in ]; then
	cp params.in $GP3DSOURCELOC
else
	cp $GP3DSOURCELOC/params.in.dist $GP3DSOURCELOC/params.in
fi
#Take care of any ic.in changes
if [ -a ic.in ]; then
	cp ic.in $GP3DSOURCELOC
fi

#Change to code dir
origdir=${PWD}
pushd $GP3DSOURCELOC
#Compile.
make
#Setup dir
#if [ $? == 0 ]; then
mv gp $origdir
cp params.in "run.$TYPE" $origdir
rm *.mod params.in ic.in
#fi
make clean
#go back
popd
chmod +x gp
chmod +x "run.$TYPE"
